(defun weekday(n)
  (cond ( (= n 0) 'Sunday)
     ( (= n 1) 'Monday)
     ( (= n 2) 'Tuesday)
     ( (= n 3) 'Wednesday)
     ( (= n 4) 'Thursday)
     ( (= n 5) 'Friday)
     ( T 'Saturday)))

(defun zeller(y m day)
  (let* ( (roman-month (if (< m 3) (+ m 10) (- m 2)))
          (roman-year (if (< m 3) (- y 1) y))
          (century (floor roman-year 100))
          (decade (mod roman-year 100)) )
    (weekday (mod (+ day decade
                     (floor (- (* 13 roman-month) 1) 5)
                     (floor decade 4)
                     (floor century 4)
                     (* century -2)) 7)) ))
